// Generated by tools/generate-custom-properties.mjs; do not edit.
#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace blendx {

enum class CustomPropertyInvalidation : uint8_t { kPaint, kMeasure, kSpecial };
enum class CustomPropertyId : uint16_t {
  kItemHeight,
  kOverdraw,
  kEstimatedItemHeight,
  kAlignment,
  kFollowTail,
  kSrc,
  kAlt,
  kObjectFit,
  kCommands,
  kSource,
  kCode,
  kLanguage,
  kShowLineNumbers,
  kShowHeader,
  kPatch,
  kWordDiff,
  kValue,
  kMax,
  kAnimationDurationMs,
  kAnimationLoop,
  kAnimationAlternate,
  kAnimateValue,
  kAnimateOpacity,
  kPlaceholder,
  kReadOnly,
  kPassword,
  kSelectable,
  kMinRows,
  kMaxRows,
  kAutoFocus,
  kPosition,
  kSide,
  kAlign,
  kAnchor,
  kOffset,
  kAnchorGap,
  kAnchorId,
  kTabIndex,
  kDisabled,
  kModal,
  kAccessibilityRole,
  kAccessibilityLabel,
  kAccessibilityDescription,
  kAccessibilityValue,
  kAccessibilityChecked,
  kAccessibilitySelected,
};
struct CustomPropertyDefinition {
  CustomPropertyId id;
  std::string_view name;
  CustomPropertyInvalidation invalidation;
};
inline constexpr std::array<CustomPropertyDefinition, 46> kCustomProperties = {{
  {CustomPropertyId::kItemHeight, "itemHeight", CustomPropertyInvalidation::kMeasure},
  {CustomPropertyId::kOverdraw, "overdraw", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kEstimatedItemHeight, "estimatedItemHeight", CustomPropertyInvalidation::kMeasure},
  {CustomPropertyId::kAlignment, "alignment", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kFollowTail, "followTail", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kSrc, "src", CustomPropertyInvalidation::kMeasure},
  {CustomPropertyId::kAlt, "alt", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kObjectFit, "objectFit", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kCommands, "commands", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kSource, "source", CustomPropertyInvalidation::kMeasure},
  {CustomPropertyId::kCode, "code", CustomPropertyInvalidation::kMeasure},
  {CustomPropertyId::kLanguage, "language", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kShowLineNumbers, "showLineNumbers", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kShowHeader, "showHeader", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kPatch, "patch", CustomPropertyInvalidation::kMeasure},
  {CustomPropertyId::kWordDiff, "wordDiff", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kValue, "value", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kMax, "max", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAnimationDurationMs, "animationDurationMs", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAnimationLoop, "animationLoop", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAnimationAlternate, "animationAlternate", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAnimateValue, "animateValue", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAnimateOpacity, "animateOpacity", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kPlaceholder, "placeholder", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kReadOnly, "readOnly", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kPassword, "password", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kSelectable, "selectable", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kMinRows, "minRows", CustomPropertyInvalidation::kMeasure},
  {CustomPropertyId::kMaxRows, "maxRows", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAutoFocus, "autoFocus", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kPosition, "position", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kSide, "side", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kAlign, "align", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kAnchor, "anchor", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kOffset, "offset", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kAnchorGap, "anchorGap", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kAnchorId, "anchorId", CustomPropertyInvalidation::kSpecial},
  {CustomPropertyId::kTabIndex, "tabIndex", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kDisabled, "disabled", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kModal, "modal", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAccessibilityRole, "accessibilityRole", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAccessibilityLabel, "accessibilityLabel", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAccessibilityDescription, "accessibilityDescription", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAccessibilityValue, "accessibilityValue", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAccessibilityChecked, "accessibilityChecked", CustomPropertyInvalidation::kPaint},
  {CustomPropertyId::kAccessibilitySelected, "accessibilitySelected", CustomPropertyInvalidation::kPaint},
}};
inline constexpr const CustomPropertyDefinition* find_custom_property(std::string_view name) {
  for (const auto& property : kCustomProperties) if (property.name == name) return &property;
  return nullptr;
}

}  // namespace blendx
